dataset_name: ghananlpcommunity/ghana-english-asr-2700hrs
text_column: corrected_text
audio_column: audio
duration_column: duration_ss
sample_rate: 16000
max_duration_train: 20.0
max_duration_eval: 30.0
min_duration: 0.5
test_size: 0.02
val_size: 0.02
seed: 42
num_proc: 4